import { describe, expect, it, beforeAll, afterAll } from "vitest";

// Integration test — requires a real Postgres (same pattern as the other
// tests/*.test.ts integration suites).
const hasDb = Boolean(process.env.DATABASE_URL);

describe.skipIf(!hasDb)("lib/tasks.ts (admin/uppgifter complete/dismiss/manual-create)", () => {
  let prisma: import("@prisma/client").PrismaClient;
  let setTaskStatus: typeof import("@/lib/tasks").setTaskStatus;
  let createManualTask: typeof import("@/lib/tasks").createManualTask;
  let getTaskForSession: typeof import("@/lib/tasks").getTaskForSession;

  beforeAll(async () => {
    const { PrismaClient } = await import("@prisma/client");
    prisma = new PrismaClient();
    ({ setTaskStatus, createManualTask, getTaskForSession } = await import("@/lib/tasks"));
  });

  afterAll(async () => {
    await prisma.$disconnect();
  });

  const owner = { role: "OWNER" as const, partnerId: null };

  it("marks a task DONE with a completedAt timestamp", async () => {
    const task = await prisma.followUpTask.create({
      data: { type: "CUSTOM", title: "Test task", dueDate: new Date() },
    });

    const updated = await setTaskStatus(owner, task.id, "DONE");
    expect(updated?.status).toBe("DONE");
    expect(updated?.completedAt).not.toBeNull();

    await prisma.followUpTask.delete({ where: { id: task.id } });
  });

  it("dismisses a task with no completedAt", async () => {
    const task = await prisma.followUpTask.create({
      data: { type: "CUSTOM", title: "Test task", dueDate: new Date() },
    });

    const updated = await setTaskStatus(owner, task.id, "DISMISSED");
    expect(updated?.status).toBe("DISMISSED");
    expect(updated?.completedAt).toBeNull();

    await prisma.followUpTask.delete({ where: { id: task.id } });
  });

  it("a PARTNER session cannot complete a task assigned to a different partner", async () => {
    const partnerA = await prisma.partner.create({ data: { name: `Partner A ${Date.now()}` } });
    const partnerB = await prisma.partner.create({ data: { name: `Partner B ${Date.now()}` } });
    const task = await prisma.followUpTask.create({
      data: { type: "CUSTOM", title: "Scoped task", dueDate: new Date(), partnerId: partnerA.id },
    });

    const sessionForB = { role: "PARTNER" as const, partnerId: partnerB.id };
    expect(await getTaskForSession(sessionForB, task.id)).toBeNull();
    expect(await setTaskStatus(sessionForB, task.id, "DONE")).toBeNull();

    const unchanged = await prisma.followUpTask.findUniqueOrThrow({ where: { id: task.id } });
    expect(unchanged.status).toBe("PENDING");

    await prisma.followUpTask.delete({ where: { id: task.id } });
    await prisma.partner.delete({ where: { id: partnerA.id } });
    await prisma.partner.delete({ where: { id: partnerB.id } });
  });

  it("the assigned partner CAN complete their own task", async () => {
    const partner = await prisma.partner.create({ data: { name: `Partner ${Date.now()}` } });
    const task = await prisma.followUpTask.create({
      data: { type: "CUSTOM", title: "My task", dueDate: new Date(), partnerId: partner.id },
    });

    const sessionForPartner = { role: "PARTNER" as const, partnerId: partner.id };
    const updated = await setTaskStatus(sessionForPartner, task.id, "DONE");
    expect(updated?.status).toBe("DONE");

    await prisma.followUpTask.delete({ where: { id: task.id } });
    await prisma.partner.delete({ where: { id: partner.id } });
  });

  it("createManualTask rejects a PARTNER session", async () => {
    await expect(
      createManualTask(
        { role: "PARTNER", partnerId: "some-partner" },
        { title: "X", dueDate: new Date() },
      ),
    ).rejects.toThrow();
  });

  it("createManualTask creates a CUSTOM, non-auto-generated task", async () => {
    const task = await createManualTask(owner, {
      title: "Ring styrelsen",
      dueDate: new Date("2027-01-01"),
    });
    expect(task.type).toBe("CUSTOM");
    expect(task.autoGenerated).toBe(false);

    await prisma.followUpTask.delete({ where: { id: task.id } });
  });
});
