import { LeadStatus, Prisma, ProjectStatus, ServiceType, TaskType } from "@prisma/client";
import { prisma } from "@/lib/prisma";

// Follow-up generation rules (architecture.md §4.6). This is the mechanism
// that makes the 2-year/5-year garantibesiktning and recurring OVK cycles
// automatic instead of something a human has to remember.

const STAMBYTE_SCALE_SERVICES: ServiceType[] = [
  ServiceType.KONTROLLANSVARIG,
  ServiceType.ENTREPRENADBESIKTNING,
];

function addMonths(date: Date, months: number): Date {
  const result = new Date(date);
  result.setMonth(result.getMonth() + months);
  return result;
}

/**
 * Call this after marking a Project SLUTFORD with a completedDate.
 * Idempotent: skips creation if a matching auto-generated task already
 * exists for the project.
 */
export async function generateFollowUpTasksForProject(projectId: string): Promise<void> {
  const project = await prisma.project.findUniqueOrThrow({
    where: { id: projectId },
    include: { customer: true },
  });

  if (project.status !== ProjectStatus.SLUTFORD || !project.completedDate) {
    throw new Error("Project must be SLUTFORD with a completedDate to generate follow-ups");
  }

  const tasksToCreate: Prisma.FollowUpTaskCreateManyInput[] = [];

  if (STAMBYTE_SCALE_SERVICES.includes(project.serviceType)) {
    tasksToCreate.push(
      {
        type: TaskType.GARANTI_2AR,
        dueDate: addMonths(project.completedDate, 21),
        title: `Boka 2-årsbesiktning – ${project.customer.brfNamn}`,
        projectId: project.id,
        customerId: project.customerId,
        partnerId: project.partnerId,
        autoGenerated: true,
      },
      {
        type: TaskType.GARANTI_5AR,
        dueDate: addMonths(project.completedDate, 57),
        title: `Boka 5-årsbesiktning – ${project.customer.brfNamn}`,
        projectId: project.id,
        customerId: project.customerId,
        partnerId: project.partnerId,
        autoGenerated: true,
      },
    );
  }

  if (project.serviceType === ServiceType.OVK) {
    const intervalYears = project.customer.ovkIntervalYears;
    const flagUnknownInterval = intervalYears == null;
    const monthsUntilDue = flagUnknownInterval ? 33 : intervalYears! * 12 - 3;

    tasksToCreate.push({
      type: TaskType.OVK_ATERKOMMANDE,
      dueDate: addMonths(project.completedDate, monthsUntilDue),
      title: flagUnknownInterval
        ? `Boka nästa OVK – ${project.customer.brfNamn} (intervall ej satt – bekräfta 3 eller 6 år)`
        : `Boka nästa OVK – ${project.customer.brfNamn}`,
      projectId: project.id,
      customerId: project.customerId,
      partnerId: project.partnerId,
      autoGenerated: true,
    });
  }

  for (const task of tasksToCreate) {
    const existing = await prisma.followUpTask.findFirst({
      where: { projectId: task.projectId, type: task.type, autoGenerated: true },
    });
    if (!existing) {
      await prisma.followUpTask.create({ data: task });
    }
  }
}

/** Auto follow-up on every new lead: contact within 3 business days. */
function addBusinessDays(date: Date, days: number): Date {
  const result = new Date(date);
  let added = 0;
  while (added < days) {
    result.setDate(result.getDate() + 1);
    const day = result.getDay();
    if (day !== 0 && day !== 6) added += 1;
  }
  return result;
}

export async function createLeadFollowUpTask(leadId: string, brfNamn: string): Promise<void> {
  const existing = await prisma.followUpTask.findFirst({
    where: { leadId, type: TaskType.LEAD_UPPFOLJNING, autoGenerated: true },
  });
  if (existing) return;

  await prisma.followUpTask.create({
    data: {
      type: TaskType.LEAD_UPPFOLJNING,
      dueDate: addBusinessDays(new Date(), 3),
      title: `Följ upp lead – ${brfNamn}`,
      leadId,
      autoGenerated: true,
    },
  });
}

/**
 * Belt-and-braces sweep (architecture.md §6.4 step 3): catches any NEW
 * lead that somehow ended up without a LEAD_UPPFOLJNING task — e.g. if
 * createLeadFollowUpTask failed silently after lead creation succeeded.
 * Safe to run daily; createLeadFollowUpTask is already idempotent per lead.
 */
export async function sweepMissingLeadFollowUps(): Promise<number> {
  const leadsWithoutTask = await prisma.lead.findMany({
    where: { status: LeadStatus.NEW, tasks: { none: { type: TaskType.LEAD_UPPFOLJNING } } },
  });

  for (const lead of leadsWithoutTask) {
    await createLeadFollowUpTask(lead.id, lead.brfNamn);
  }

  return leadsWithoutTask.length;
}
