import { prisma } from "@/lib/prisma";
import { AccessSession, followUpTaskWhereForSession, assertOwner } from "@/lib/access";
import { TaskStatus, TaskType } from "@prisma/client";

export async function listTasksForSession(
  session: AccessSession,
  status: TaskStatus = TaskStatus.PENDING,
) {
  return prisma.followUpTask.findMany({
    where: { ...followUpTaskWhereForSession(session), status },
    orderBy: { dueDate: "asc" },
    include: { customer: true, lead: true, partner: true },
  });
}

export async function getTaskForSession(session: AccessSession, id: string) {
  return prisma.followUpTask.findFirst({
    where: { id, ...followUpTaskWhereForSession(session) },
  });
}

/**
 * OWNER or the partner a task is assigned to can complete/dismiss it —
 * same rationale as markProjectCompleted in lib/projects.ts: whoever is
 * scoped to see the task is the one who'd actually be doing the work it
 * represents.
 */
export async function setTaskStatus(
  session: AccessSession,
  id: string,
  status: Extract<TaskStatus, "DONE" | "DISMISSED">,
) {
  const task = await getTaskForSession(session, id);
  if (!task) return null;

  return prisma.followUpTask.update({
    where: { id },
    data: { status, completedAt: status === TaskStatus.DONE ? new Date() : null },
  });
}

export interface CreateManualTaskInput {
  title: string;
  dueDate: Date;
  description?: string | null;
  leadId?: string | null;
  customerId?: string | null;
  projectId?: string | null;
  partnerId?: string | null;
}

/**
 * OWNER-only: manual follow-ups (architecture.md §3 "Manual task
 * creation") are a triage decision, same rationale as assignLeadToPartner
 * — a PARTNER session shouldn't be able to create tasks assigned to
 * themselves or anyone else unprompted.
 */
export async function createManualTask(session: AccessSession, input: CreateManualTaskInput) {
  assertOwner(session);

  return prisma.followUpTask.create({
    data: {
      type: TaskType.CUSTOM,
      dueDate: input.dueDate,
      title: input.title,
      description: input.description ?? null,
      leadId: input.leadId ?? null,
      customerId: input.customerId ?? null,
      projectId: input.projectId ?? null,
      partnerId: input.partnerId ?? null,
      autoGenerated: false,
    },
  });
}
