import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { followUpTaskWhereForSession } from "@/lib/access";
import { TaskStatus } from "@prisma/client";

export default async function UppgifterPage() {
  const session = await auth();
  if (!session?.user) return null;

  const tasks = await prisma.followUpTask.findMany({
    where: { ...followUpTaskWhereForSession(session.user), status: TaskStatus.PENDING },
    orderBy: { dueDate: "asc" },
    include: { customer: true, lead: true },
  });

  return (
    <div>
      <h1 className="text-2xl font-semibold text-slate-900">Uppgifter</h1>
      <ul className="mt-6 space-y-3">
        {tasks.map((task) => (
          <li key={task.id} className="rounded-lg border border-slate-200 bg-white p-4">
            <p className="font-medium text-slate-900">{task.title}</p>
            <p className="mt-1 text-sm text-slate-500">
              Förfaller: {task.dueDate.toLocaleDateString("sv-SE")}
              {task.autoGenerated ? " · automatiskt genererad" : ""}
            </p>
          </li>
        ))}
        {tasks.length === 0 && <p className="text-slate-400">Inga väntande uppgifter.</p>}
      </ul>
    </div>
  );
}
