import { revalidatePath } from "next/cache";
import Link from "next/link";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { createManualTask, listTasksForSession, setTaskStatus } from "@/lib/tasks";
import { TaskStatus } from "@prisma/client";

export default async function UppgifterPage() {
  const session = await auth();
  if (!session?.user) return null;

  const tasks = await listTasksForSession(session.user, TaskStatus.PENDING);
  const [customers, partners] =
    session.user.role === "OWNER"
      ? await Promise.all([prisma.customer.findMany(), prisma.partner.findMany()])
      : [[], []];

  async function completeTask(formData: FormData) {
    "use server";
    const currentSession = await auth();
    if (!currentSession?.user) return;
    const taskId = formData.get("taskId") as string;
    const status = formData.get("status") as "DONE" | "DISMISSED";
    await setTaskStatus(currentSession.user, taskId, status);
    revalidatePath("/admin/uppgifter");
  }

  async function addTask(formData: FormData) {
    "use server";
    const currentSession = await auth();
    if (!currentSession?.user) return;
    const dueDateRaw = formData.get("dueDate") as string;
    if (!dueDateRaw) return;

    await createManualTask(currentSession.user, {
      title: formData.get("title") as string,
      dueDate: new Date(dueDateRaw),
      description: (formData.get("description") as string) || null,
      customerId: (formData.get("customerId") as string) || null,
      partnerId: (formData.get("partnerId") as string) || null,
    });
    revalidatePath("/admin/uppgifter");
  }

  return (
    <div>
      <h1 className="text-2xl font-semibold text-slate-900">Uppgifter</h1>
      <ul className="mt-6 space-y-3">
        {tasks.map((task) => (
          <li key={task.id} className="rounded-lg border border-slate-200 bg-white p-4">
            <p className="font-medium text-slate-900">{task.title}</p>
            <p className="mt-1 text-sm text-slate-500">
              Förfaller: {task.dueDate.toLocaleDateString("sv-SE")}
              {task.autoGenerated ? " · automatiskt genererad" : ""}
              {task.customer && (
                <>
                  {" · "}
                  <Link href={`/admin/kunder/${task.customer.id}`} className="text-blue-800 hover:underline">
                    {task.customer.brfNamn}
                  </Link>
                </>
              )}
              {task.lead && (
                <>
                  {" · "}
                  <Link href={`/admin/leads/${task.lead.id}`} className="text-blue-800 hover:underline">
                    {task.lead.brfNamn}
                  </Link>
                </>
              )}
            </p>
            <div className="mt-3 flex gap-3 text-sm">
              <form action={completeTask}>
                <input type="hidden" name="taskId" value={task.id} />
                <input type="hidden" name="status" value="DONE" />
                <button type="submit" className="text-blue-800 hover:underline">
                  Markera klar
                </button>
              </form>
              <form action={completeTask}>
                <input type="hidden" name="taskId" value={task.id} />
                <input type="hidden" name="status" value="DISMISSED" />
                <button type="submit" className="text-slate-500 hover:underline">
                  Avfärda
                </button>
              </form>
            </div>
          </li>
        ))}
        {tasks.length === 0 && <p className="text-slate-500">Inga väntande uppgifter.</p>}
      </ul>

      {session.user.role === "OWNER" && (
        <div className="mt-8 rounded-lg border border-slate-200 bg-white p-5">
          <h2 className="font-medium text-slate-900">Ny uppgift</h2>
          <form action={addTask} className="mt-4 grid gap-4 sm:grid-cols-2">
            <div className="sm:col-span-2">
              <label htmlFor="title" className="block text-sm font-medium text-slate-700">
                Titel
              </label>
              <input
                id="title"
                name="title"
                required
                className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2"
              />
            </div>
            <div>
              <label htmlFor="dueDate" className="block text-sm font-medium text-slate-700">
                Förfallodatum
              </label>
              <input
                id="dueDate"
                name="dueDate"
                type="date"
                required
                className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2"
              />
            </div>
            <div>
              <label htmlFor="customerId" className="block text-sm font-medium text-slate-700">
                Kund (valfritt)
              </label>
              <select
                id="customerId"
                name="customerId"
                defaultValue=""
                className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2"
              >
                <option value="">Ingen</option>
                {customers.map((customer) => (
                  <option key={customer.id} value={customer.id}>
                    {customer.brfNamn}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label htmlFor="partnerId" className="block text-sm font-medium text-slate-700">
                Partner (valfritt)
              </label>
              <select
                id="partnerId"
                name="partnerId"
                defaultValue=""
                className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2"
              >
                <option value="">Ingen</option>
                {partners.map((partner) => (
                  <option key={partner.id} value={partner.id}>
                    {partner.name}
                  </option>
                ))}
              </select>
            </div>
            <div className="sm:col-span-2">
              <label htmlFor="description" className="block text-sm font-medium text-slate-700">
                Beskrivning (valfritt)
              </label>
              <textarea
                id="description"
                name="description"
                rows={2}
                className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2"
              />
            </div>
            <div className="sm:col-span-2">
              <button
                type="submit"
                className="rounded-md bg-blue-800 px-5 py-2.5 text-sm font-medium text-white hover:bg-blue-900"
              >
                Lägg till uppgift
              </button>
            </div>
          </form>
        </div>
      )}
    </div>
  );
}
